package com.mrbt.insurance.webset.mapper;

import com.mrbt.insurance.webset.model.CompanyOccupation;
import com.mrbt.insurance.webset.model.CompanyOccupationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyOccupationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_occupation
     *
     * @mbggenerated
     */
    int countByExample(CompanyOccupationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_occupation
     *
     * @mbggenerated
     */
    int deleteByExample(CompanyOccupationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_occupation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_occupation
     *
     * @mbggenerated
     */
    int insert(CompanyOccupation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_occupation
     *
     * @mbggenerated
     */
    int insertSelective(CompanyOccupation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_occupation
     *
     * @mbggenerated
     */
    List<CompanyOccupation> selectByExample(CompanyOccupationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_occupation
     *
     * @mbggenerated
     */
    CompanyOccupation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_occupation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CompanyOccupation record, @Param("example") CompanyOccupationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_occupation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CompanyOccupation record, @Param("example") CompanyOccupationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_occupation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompanyOccupation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_occupation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompanyOccupation record);
}