package com.mrbt.insurance.webset.mapper;

import com.mrbt.insurance.webset.model.CompanyType;
import com.mrbt.insurance.webset.model.CompanyTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_type
     *
     * @mbggenerated
     */
    int countByExample(CompanyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_type
     *
     * @mbggenerated
     */
    int deleteByExample(CompanyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_type
     *
     * @mbggenerated
     */
    int insert(CompanyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_type
     *
     * @mbggenerated
     */
    int insertSelective(CompanyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_type
     *
     * @mbggenerated
     */
    List<CompanyType> selectByExample(CompanyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_type
     *
     * @mbggenerated
     */
    CompanyType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CompanyType record, @Param("example") CompanyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CompanyType record, @Param("example") CompanyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompanyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompanyType record);
}