package com.mrbt.insurance.webset.mapper;

import com.mrbt.insurance.webset.model.CustomerServiceLog;
import com.mrbt.insurance.webset.model.CustomerServiceLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerServiceLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service_log
     *
     * @mbggenerated
     */
    int countByExample(CustomerServiceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service_log
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerServiceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service_log
     *
     * @mbggenerated
     */
    int insert(CustomerServiceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service_log
     *
     * @mbggenerated
     */
    int insertSelective(CustomerServiceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service_log
     *
     * @mbggenerated
     */
    List<CustomerServiceLog> selectByExample(CustomerServiceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service_log
     *
     * @mbggenerated
     */
    CustomerServiceLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerServiceLog record, @Param("example") CustomerServiceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerServiceLog record, @Param("example") CustomerServiceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerServiceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerServiceLog record);
}