package com.mrbt.insurance.webset.mapper;

import com.mrbt.insurance.webset.model.EmployeeInfo;
import com.mrbt.insurance.webset.model.EmployeeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    int countByExample(EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    int deleteByExample(EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    int insert(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    int insertSelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    List<EmployeeInfo> selectByExample(EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    EmployeeInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EmployeeInfo record, @Param("example") EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EmployeeInfo record, @Param("example") EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmployeeInfo record);
}