package com.mrbt.insurance.webset.mapper;

import com.mrbt.insurance.webset.model.Ordersinfo;
import com.mrbt.insurance.webset.model.OrdersinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    int countByExample(OrdersinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    int deleteByExample(OrdersinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    int insert(Ordersinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    int insertSelective(Ordersinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    List<Ordersinfo> selectByExample(OrdersinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    Ordersinfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Ordersinfo record, @Param("example") OrdersinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Ordersinfo record, @Param("example") OrdersinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Ordersinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ordersinfo record);
}