package com.mrbt.insurance.webset.mapper;

import com.mrbt.insurance.webset.model.TrafficWebsite;
import com.mrbt.insurance.webset.model.TrafficWebsiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrafficWebsiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_website
     *
     * @mbggenerated
     */
    int countByExample(TrafficWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_website
     *
     * @mbggenerated
     */
    int deleteByExample(TrafficWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_website
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_website
     *
     * @mbggenerated
     */
    int insert(TrafficWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_website
     *
     * @mbggenerated
     */
    int insertSelective(TrafficWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_website
     *
     * @mbggenerated
     */
    List<TrafficWebsite> selectByExample(TrafficWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_website
     *
     * @mbggenerated
     */
    TrafficWebsite selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_website
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TrafficWebsite record, @Param("example") TrafficWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_website
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TrafficWebsite record, @Param("example") TrafficWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_website
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TrafficWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_website
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TrafficWebsite record);
}