package com.mrbt.insurance.webset.mapper;

import com.mrbt.insurance.webset.model.UsersIntegralInfo;
import com.mrbt.insurance.webset.model.UsersIntegralInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersIntegralInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_integral_info
     *
     * @mbggenerated
     */
    int countByExample(UsersIntegralInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_integral_info
     *
     * @mbggenerated
     */
    int deleteByExample(UsersIntegralInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_integral_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_integral_info
     *
     * @mbggenerated
     */
    int insert(UsersIntegralInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_integral_info
     *
     * @mbggenerated
     */
    int insertSelective(UsersIntegralInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_integral_info
     *
     * @mbggenerated
     */
    List<UsersIntegralInfo> selectByExample(UsersIntegralInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_integral_info
     *
     * @mbggenerated
     */
    UsersIntegralInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_integral_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsersIntegralInfo record, @Param("example") UsersIntegralInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_integral_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsersIntegralInfo record, @Param("example") UsersIntegralInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_integral_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsersIntegralInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_integral_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsersIntegralInfo record);
}