package com.mrbt.insurance.webset.mapper;

import com.mrbt.insurance.webset.model.UsersDocumentInfo;
import com.mrbt.insurance.webset.model.UsersDocumentInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersDocumentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_document_info
     *
     * @mbggenerated
     */
    int countByExample(UsersDocumentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_document_info
     *
     * @mbggenerated
     */
    int deleteByExample(UsersDocumentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_document_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_document_info
     *
     * @mbggenerated
     */
    int insert(UsersDocumentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_document_info
     *
     * @mbggenerated
     */
    int insertSelective(UsersDocumentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_document_info
     *
     * @mbggenerated
     */
    List<UsersDocumentInfo> selectByExample(UsersDocumentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_document_info
     *
     * @mbggenerated
     */
    UsersDocumentInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_document_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsersDocumentInfo record, @Param("example") UsersDocumentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_document_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsersDocumentInfo record, @Param("example") UsersDocumentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_document_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsersDocumentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_document_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsersDocumentInfo record);
}