package com.mrbt.insurance.webset.mapper;

import com.mrbt.insurance.webset.model.UsersPolicyHolder;
import com.mrbt.insurance.webset.model.UsersPolicyHolderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersPolicyHolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_policy_holder
     *
     * @mbggenerated
     */
    int countByExample(UsersPolicyHolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_policy_holder
     *
     * @mbggenerated
     */
    int deleteByExample(UsersPolicyHolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_policy_holder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_policy_holder
     *
     * @mbggenerated
     */
    int insert(UsersPolicyHolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_policy_holder
     *
     * @mbggenerated
     */
    int insertSelective(UsersPolicyHolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_policy_holder
     *
     * @mbggenerated
     */
    List<UsersPolicyHolder> selectByExample(UsersPolicyHolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_policy_holder
     *
     * @mbggenerated
     */
    UsersPolicyHolder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_policy_holder
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsersPolicyHolder record, @Param("example") UsersPolicyHolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_policy_holder
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsersPolicyHolder record, @Param("example") UsersPolicyHolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_policy_holder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsersPolicyHolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_policy_holder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsersPolicyHolder record);
}