package com.mrbt.insurance.webset.model;

public class CompanyType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.tname
     *
     * @mbggenerated
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.type_desc
     *
     * @mbggenerated
     */
    private String typeDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.id
     *
     * @return the value of company_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.id
     *
     * @param id the value for company_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.tname
     *
     * @return the value of company_type.tname
     *
     * @mbggenerated
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.tname
     *
     * @param tname the value for company_type.tname
     *
     * @mbggenerated
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.type_desc
     *
     * @return the value of company_type.type_desc
     *
     * @mbggenerated
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.type_desc
     *
     * @param typeDesc the value for company_type.type_desc
     *
     * @mbggenerated
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc == null ? null : typeDesc.trim();
    }
}