package com.mrbt.insurance.webset.model;

public class CompanyOccupation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_occupation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_occupation.oname
     *
     * @mbggenerated
     */
    private String oname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_occupation.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_occupation.comp_id
     *
     * @mbggenerated
     */
    private Integer compId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_occupation.id
     *
     * @return the value of company_occupation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_occupation.id
     *
     * @param id the value for company_occupation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_occupation.oname
     *
     * @return the value of company_occupation.oname
     *
     * @mbggenerated
     */
    public String getOname() {
        return oname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_occupation.oname
     *
     * @param oname the value for company_occupation.oname
     *
     * @mbggenerated
     */
    public void setOname(String oname) {
        this.oname = oname == null ? null : oname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_occupation.level
     *
     * @return the value of company_occupation.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_occupation.level
     *
     * @param level the value for company_occupation.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_occupation.comp_id
     *
     * @return the value of company_occupation.comp_id
     *
     * @mbggenerated
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_occupation.comp_id
     *
     * @param compId the value for company_occupation.comp_id
     *
     * @mbggenerated
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }
}