package com.mrbt.insurance.webset.model;

public class CompanyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.comp_code
     *
     * @mbggenerated
     */
    private String compCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.type_id
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.details
     *
     * @mbggenerated
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.id
     *
     * @return the value of company_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.id
     *
     * @param id the value for company_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.cname
     *
     * @return the value of company_info.cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.cname
     *
     * @param cname the value for company_info.cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.comp_code
     *
     * @return the value of company_info.comp_code
     *
     * @mbggenerated
     */
    public String getCompCode() {
        return compCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.comp_code
     *
     * @param compCode the value for company_info.comp_code
     *
     * @mbggenerated
     */
    public void setCompCode(String compCode) {
        this.compCode = compCode == null ? null : compCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.type_id
     *
     * @return the value of company_info.type_id
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.type_id
     *
     * @param typeId the value for company_info.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.details
     *
     * @return the value of company_info.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.details
     *
     * @param details the value for company_info.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.logo
     *
     * @return the value of company_info.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.logo
     *
     * @param logo the value for company_info.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }
}