package com.mrbt.insurance.webset.model;

import java.util.Date;

public class CustomerServiceLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.reply_name
     *
     * @mbggenerated
     */
    private String replyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.reply_time
     *
     * @mbggenerated
     */
    private Date replyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.reply_result
     *
     * @mbggenerated
     */
    private String replyResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.visit_name
     *
     * @mbggenerated
     */
    private String visitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.visit_time
     *
     * @mbggenerated
     */
    private Date visitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service_log.visit_result
     *
     * @mbggenerated
     */
    private String visitResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.id
     *
     * @return the value of customer_service_log.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.id
     *
     * @param id the value for customer_service_log.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.type
     *
     * @return the value of customer_service_log.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.type
     *
     * @param type the value for customer_service_log.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.uname
     *
     * @return the value of customer_service_log.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.uname
     *
     * @param uname the value for customer_service_log.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.telephone
     *
     * @return the value of customer_service_log.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.telephone
     *
     * @param telephone the value for customer_service_log.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.email
     *
     * @return the value of customer_service_log.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.email
     *
     * @param email the value for customer_service_log.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.create_time
     *
     * @return the value of customer_service_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.create_time
     *
     * @param createTime the value for customer_service_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.reply_name
     *
     * @return the value of customer_service_log.reply_name
     *
     * @mbggenerated
     */
    public String getReplyName() {
        return replyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.reply_name
     *
     * @param replyName the value for customer_service_log.reply_name
     *
     * @mbggenerated
     */
    public void setReplyName(String replyName) {
        this.replyName = replyName == null ? null : replyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.reply_time
     *
     * @return the value of customer_service_log.reply_time
     *
     * @mbggenerated
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.reply_time
     *
     * @param replyTime the value for customer_service_log.reply_time
     *
     * @mbggenerated
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.reply_result
     *
     * @return the value of customer_service_log.reply_result
     *
     * @mbggenerated
     */
    public String getReplyResult() {
        return replyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.reply_result
     *
     * @param replyResult the value for customer_service_log.reply_result
     *
     * @mbggenerated
     */
    public void setReplyResult(String replyResult) {
        this.replyResult = replyResult == null ? null : replyResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.visit_name
     *
     * @return the value of customer_service_log.visit_name
     *
     * @mbggenerated
     */
    public String getVisitName() {
        return visitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.visit_name
     *
     * @param visitName the value for customer_service_log.visit_name
     *
     * @mbggenerated
     */
    public void setVisitName(String visitName) {
        this.visitName = visitName == null ? null : visitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.visit_time
     *
     * @return the value of customer_service_log.visit_time
     *
     * @mbggenerated
     */
    public Date getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.visit_time
     *
     * @param visitTime the value for customer_service_log.visit_time
     *
     * @mbggenerated
     */
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service_log.visit_result
     *
     * @return the value of customer_service_log.visit_result
     *
     * @mbggenerated
     */
    public String getVisitResult() {
        return visitResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service_log.visit_result
     *
     * @param visitResult the value for customer_service_log.visit_result
     *
     * @mbggenerated
     */
    public void setVisitResult(String visitResult) {
        this.visitResult = visitResult == null ? null : visitResult.trim();
    }
}