package com.mrbt.insurance.webset.model;

import java.util.Date;

public class EmployeeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.ename
     *
     * @mbggenerated
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.entry_time
     *
     * @mbggenerated
     */
    private Date entryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.estats
     *
     * @mbggenerated
     */
    private Integer estats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.departure_time
     *
     * @mbggenerated
     */
    private Date departureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.resume
     *
     * @mbggenerated
     */
    private String resume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.id
     *
     * @return the value of employee_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.id
     *
     * @param id the value for employee_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.ename
     *
     * @return the value of employee_info.ename
     *
     * @mbggenerated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.ename
     *
     * @param ename the value for employee_info.ename
     *
     * @mbggenerated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.sex
     *
     * @return the value of employee_info.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.sex
     *
     * @param sex the value for employee_info.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.entry_time
     *
     * @return the value of employee_info.entry_time
     *
     * @mbggenerated
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.entry_time
     *
     * @param entryTime the value for employee_info.entry_time
     *
     * @mbggenerated
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.estats
     *
     * @return the value of employee_info.estats
     *
     * @mbggenerated
     */
    public Integer getEstats() {
        return estats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.estats
     *
     * @param estats the value for employee_info.estats
     *
     * @mbggenerated
     */
    public void setEstats(Integer estats) {
        this.estats = estats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.departure_time
     *
     * @return the value of employee_info.departure_time
     *
     * @mbggenerated
     */
    public Date getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.departure_time
     *
     * @param departureTime the value for employee_info.departure_time
     *
     * @mbggenerated
     */
    public void setDepartureTime(Date departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.birthday
     *
     * @return the value of employee_info.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.birthday
     *
     * @param birthday the value for employee_info.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.resume
     *
     * @return the value of employee_info.resume
     *
     * @mbggenerated
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.resume
     *
     * @param resume the value for employee_info.resume
     *
     * @mbggenerated
     */
    public void setResume(String resume) {
        this.resume = resume == null ? null : resume.trim();
    }
}