package com.mrbt.insurance.webset.model;

public class EmployeeordersNexus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_orders_nexus.employee_id
     *
     * @mbggenerated
     */
    private String employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_orders_nexus.orders_id
     *
     * @mbggenerated
     */
    private String ordersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_orders_nexus.commission
     *
     * @mbggenerated
     */
    private Double commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_orders_nexus.nexus_states
     *
     * @mbggenerated
     */
    private Integer nexusStates;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_orders_nexus.employee_id
     *
     * @return the value of employee_orders_nexus.employee_id
     *
     * @mbggenerated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_orders_nexus.employee_id
     *
     * @param employeeId the value for employee_orders_nexus.employee_id
     *
     * @mbggenerated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_orders_nexus.orders_id
     *
     * @return the value of employee_orders_nexus.orders_id
     *
     * @mbggenerated
     */
    public String getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_orders_nexus.orders_id
     *
     * @param ordersId the value for employee_orders_nexus.orders_id
     *
     * @mbggenerated
     */
    public void setOrdersId(String ordersId) {
        this.ordersId = ordersId == null ? null : ordersId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_orders_nexus.commission
     *
     * @return the value of employee_orders_nexus.commission
     *
     * @mbggenerated
     */
    public Double getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_orders_nexus.commission
     *
     * @param commission the value for employee_orders_nexus.commission
     *
     * @mbggenerated
     */
    public void setCommission(Double commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_orders_nexus.nexus_states
     *
     * @return the value of employee_orders_nexus.nexus_states
     *
     * @mbggenerated
     */
    public Integer getNexusStates() {
        return nexusStates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_orders_nexus.nexus_states
     *
     * @param nexusStates the value for employee_orders_nexus.nexus_states
     *
     * @mbggenerated
     */
    public void setNexusStates(Integer nexusStates) {
        this.nexusStates = nexusStates;
    }
}