package com.mrbt.insurance.webset.model;

import java.util.Date;

public class Ordersinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.o_state
     *
     * @mbggenerated
     */
    private Integer oState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.policy_number
     *
     * @mbggenerated
     */
    private String policyNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.flow_number
     *
     * @mbggenerated
     */
    private String flowNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.guarantee_period
     *
     * @mbggenerated
     */
    private String guaranteePeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.payment_term
     *
     * @mbggenerated
     */
    private Integer paymentTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.insurance_amount
     *
     * @mbggenerated
     */
    private Double insuranceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.insurance_number
     *
     * @mbggenerated
     */
    private Integer insuranceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.payment_amount
     *
     * @mbggenerated
     */
    private Double paymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.transaction_date
     *
     * @mbggenerated
     */
    private Date transactionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.closing_date
     *
     * @mbggenerated
     */
    private Date closingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.applicant_id
     *
     * @mbggenerated
     */
    private String applicantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.relationship
     *
     * @mbggenerated
     */
    private Integer relationship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.relationship2
     *
     * @mbggenerated
     */
    private String relationship2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.insured_id
     *
     * @mbggenerated
     */
    private String insuredId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_info.employee_id
     *
     * @mbggenerated
     */
    private String employeeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.id
     *
     * @return the value of orders_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.id
     *
     * @param id the value for orders_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.o_state
     *
     * @return the value of orders_info.o_state
     *
     * @mbggenerated
     */
    public Integer getoState() {
        return oState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.o_state
     *
     * @param oState the value for orders_info.o_state
     *
     * @mbggenerated
     */
    public void setoState(Integer oState) {
        this.oState = oState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.policy_number
     *
     * @return the value of orders_info.policy_number
     *
     * @mbggenerated
     */
    public String getPolicyNumber() {
        return policyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.policy_number
     *
     * @param policyNumber the value for orders_info.policy_number
     *
     * @mbggenerated
     */
    public void setPolicyNumber(String policyNumber) {
        this.policyNumber = policyNumber == null ? null : policyNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.flow_number
     *
     * @return the value of orders_info.flow_number
     *
     * @mbggenerated
     */
    public String getFlowNumber() {
        return flowNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.flow_number
     *
     * @param flowNumber the value for orders_info.flow_number
     *
     * @mbggenerated
     */
    public void setFlowNumber(String flowNumber) {
        this.flowNumber = flowNumber == null ? null : flowNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.product_id
     *
     * @return the value of orders_info.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.product_id
     *
     * @param productId the value for orders_info.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.guarantee_period
     *
     * @return the value of orders_info.guarantee_period
     *
     * @mbggenerated
     */
    public String getGuaranteePeriod() {
        return guaranteePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.guarantee_period
     *
     * @param guaranteePeriod the value for orders_info.guarantee_period
     *
     * @mbggenerated
     */
    public void setGuaranteePeriod(String guaranteePeriod) {
        this.guaranteePeriod = guaranteePeriod == null ? null : guaranteePeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.payment_term
     *
     * @return the value of orders_info.payment_term
     *
     * @mbggenerated
     */
    public Integer getPaymentTerm() {
        return paymentTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.payment_term
     *
     * @param paymentTerm the value for orders_info.payment_term
     *
     * @mbggenerated
     */
    public void setPaymentTerm(Integer paymentTerm) {
        this.paymentTerm = paymentTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.insurance_amount
     *
     * @return the value of orders_info.insurance_amount
     *
     * @mbggenerated
     */
    public Double getInsuranceAmount() {
        return insuranceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.insurance_amount
     *
     * @param insuranceAmount the value for orders_info.insurance_amount
     *
     * @mbggenerated
     */
    public void setInsuranceAmount(Double insuranceAmount) {
        this.insuranceAmount = insuranceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.insurance_number
     *
     * @return the value of orders_info.insurance_number
     *
     * @mbggenerated
     */
    public Integer getInsuranceNumber() {
        return insuranceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.insurance_number
     *
     * @param insuranceNumber the value for orders_info.insurance_number
     *
     * @mbggenerated
     */
    public void setInsuranceNumber(Integer insuranceNumber) {
        this.insuranceNumber = insuranceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.payment_amount
     *
     * @return the value of orders_info.payment_amount
     *
     * @mbggenerated
     */
    public Double getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.payment_amount
     *
     * @param paymentAmount the value for orders_info.payment_amount
     *
     * @mbggenerated
     */
    public void setPaymentAmount(Double paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.transaction_date
     *
     * @return the value of orders_info.transaction_date
     *
     * @mbggenerated
     */
    public Date getTransactionDate() {
        return transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.transaction_date
     *
     * @param transactionDate the value for orders_info.transaction_date
     *
     * @mbggenerated
     */
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.start_date
     *
     * @return the value of orders_info.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.start_date
     *
     * @param startDate the value for orders_info.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.closing_date
     *
     * @return the value of orders_info.closing_date
     *
     * @mbggenerated
     */
    public Date getClosingDate() {
        return closingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.closing_date
     *
     * @param closingDate the value for orders_info.closing_date
     *
     * @mbggenerated
     */
    public void setClosingDate(Date closingDate) {
        this.closingDate = closingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.applicant_id
     *
     * @return the value of orders_info.applicant_id
     *
     * @mbggenerated
     */
    public String getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.applicant_id
     *
     * @param applicantId the value for orders_info.applicant_id
     *
     * @mbggenerated
     */
    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId == null ? null : applicantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.relationship
     *
     * @return the value of orders_info.relationship
     *
     * @mbggenerated
     */
    public Integer getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.relationship
     *
     * @param relationship the value for orders_info.relationship
     *
     * @mbggenerated
     */
    public void setRelationship(Integer relationship) {
        this.relationship = relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.relationship2
     *
     * @return the value of orders_info.relationship2
     *
     * @mbggenerated
     */
    public String getRelationship2() {
        return relationship2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.relationship2
     *
     * @param relationship2 the value for orders_info.relationship2
     *
     * @mbggenerated
     */
    public void setRelationship2(String relationship2) {
        this.relationship2 = relationship2 == null ? null : relationship2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.insured_id
     *
     * @return the value of orders_info.insured_id
     *
     * @mbggenerated
     */
    public String getInsuredId() {
        return insuredId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.insured_id
     *
     * @param insuredId the value for orders_info.insured_id
     *
     * @mbggenerated
     */
    public void setInsuredId(String insuredId) {
        this.insuredId = insuredId == null ? null : insuredId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_info.employee_id
     *
     * @return the value of orders_info.employee_id
     *
     * @mbggenerated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_info.employee_id
     *
     * @param employeeId the value for orders_info.employee_id
     *
     * @mbggenerated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }
}