package com.mrbt.insurance.webset.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OrdersinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    public OrdersinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOStateIsNull() {
            addCriterion("o_state is null");
            return (Criteria) this;
        }

        public Criteria andOStateIsNotNull() {
            addCriterion("o_state is not null");
            return (Criteria) this;
        }

        public Criteria andOStateEqualTo(Integer value) {
            addCriterion("o_state =", value, "oState");
            return (Criteria) this;
        }

        public Criteria andOStateNotEqualTo(Integer value) {
            addCriterion("o_state <>", value, "oState");
            return (Criteria) this;
        }

        public Criteria andOStateGreaterThan(Integer value) {
            addCriterion("o_state >", value, "oState");
            return (Criteria) this;
        }

        public Criteria andOStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_state >=", value, "oState");
            return (Criteria) this;
        }

        public Criteria andOStateLessThan(Integer value) {
            addCriterion("o_state <", value, "oState");
            return (Criteria) this;
        }

        public Criteria andOStateLessThanOrEqualTo(Integer value) {
            addCriterion("o_state <=", value, "oState");
            return (Criteria) this;
        }

        public Criteria andOStateIn(List<Integer> values) {
            addCriterion("o_state in", values, "oState");
            return (Criteria) this;
        }

        public Criteria andOStateNotIn(List<Integer> values) {
            addCriterion("o_state not in", values, "oState");
            return (Criteria) this;
        }

        public Criteria andOStateBetween(Integer value1, Integer value2) {
            addCriterion("o_state between", value1, value2, "oState");
            return (Criteria) this;
        }

        public Criteria andOStateNotBetween(Integer value1, Integer value2) {
            addCriterion("o_state not between", value1, value2, "oState");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberIsNull() {
            addCriterion("policy_number is null");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberIsNotNull() {
            addCriterion("policy_number is not null");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberEqualTo(String value) {
            addCriterion("policy_number =", value, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberNotEqualTo(String value) {
            addCriterion("policy_number <>", value, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberGreaterThan(String value) {
            addCriterion("policy_number >", value, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberGreaterThanOrEqualTo(String value) {
            addCriterion("policy_number >=", value, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberLessThan(String value) {
            addCriterion("policy_number <", value, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberLessThanOrEqualTo(String value) {
            addCriterion("policy_number <=", value, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberLike(String value) {
            addCriterion("policy_number like", value, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberNotLike(String value) {
            addCriterion("policy_number not like", value, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberIn(List<String> values) {
            addCriterion("policy_number in", values, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberNotIn(List<String> values) {
            addCriterion("policy_number not in", values, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberBetween(String value1, String value2) {
            addCriterion("policy_number between", value1, value2, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andPolicyNumberNotBetween(String value1, String value2) {
            addCriterion("policy_number not between", value1, value2, "policyNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberIsNull() {
            addCriterion("flow_number is null");
            return (Criteria) this;
        }

        public Criteria andFlowNumberIsNotNull() {
            addCriterion("flow_number is not null");
            return (Criteria) this;
        }

        public Criteria andFlowNumberEqualTo(String value) {
            addCriterion("flow_number =", value, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberNotEqualTo(String value) {
            addCriterion("flow_number <>", value, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberGreaterThan(String value) {
            addCriterion("flow_number >", value, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberGreaterThanOrEqualTo(String value) {
            addCriterion("flow_number >=", value, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberLessThan(String value) {
            addCriterion("flow_number <", value, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberLessThanOrEqualTo(String value) {
            addCriterion("flow_number <=", value, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberLike(String value) {
            addCriterion("flow_number like", value, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberNotLike(String value) {
            addCriterion("flow_number not like", value, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberIn(List<String> values) {
            addCriterion("flow_number in", values, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberNotIn(List<String> values) {
            addCriterion("flow_number not in", values, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberBetween(String value1, String value2) {
            addCriterion("flow_number between", value1, value2, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andFlowNumberNotBetween(String value1, String value2) {
            addCriterion("flow_number not between", value1, value2, "flowNumber");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodIsNull() {
            addCriterion("guarantee_period is null");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodIsNotNull() {
            addCriterion("guarantee_period is not null");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodEqualTo(String value) {
            addCriterion("guarantee_period =", value, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodNotEqualTo(String value) {
            addCriterion("guarantee_period <>", value, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodGreaterThan(String value) {
            addCriterion("guarantee_period >", value, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodGreaterThanOrEqualTo(String value) {
            addCriterion("guarantee_period >=", value, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodLessThan(String value) {
            addCriterion("guarantee_period <", value, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodLessThanOrEqualTo(String value) {
            addCriterion("guarantee_period <=", value, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodLike(String value) {
            addCriterion("guarantee_period like", value, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodNotLike(String value) {
            addCriterion("guarantee_period not like", value, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodIn(List<String> values) {
            addCriterion("guarantee_period in", values, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodNotIn(List<String> values) {
            addCriterion("guarantee_period not in", values, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodBetween(String value1, String value2) {
            addCriterion("guarantee_period between", value1, value2, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andGuaranteePeriodNotBetween(String value1, String value2) {
            addCriterion("guarantee_period not between", value1, value2, "guaranteePeriod");
            return (Criteria) this;
        }

        public Criteria andPaymentTermIsNull() {
            addCriterion("payment_term is null");
            return (Criteria) this;
        }

        public Criteria andPaymentTermIsNotNull() {
            addCriterion("payment_term is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentTermEqualTo(Integer value) {
            addCriterion("payment_term =", value, "paymentTerm");
            return (Criteria) this;
        }

        public Criteria andPaymentTermNotEqualTo(Integer value) {
            addCriterion("payment_term <>", value, "paymentTerm");
            return (Criteria) this;
        }

        public Criteria andPaymentTermGreaterThan(Integer value) {
            addCriterion("payment_term >", value, "paymentTerm");
            return (Criteria) this;
        }

        public Criteria andPaymentTermGreaterThanOrEqualTo(Integer value) {
            addCriterion("payment_term >=", value, "paymentTerm");
            return (Criteria) this;
        }

        public Criteria andPaymentTermLessThan(Integer value) {
            addCriterion("payment_term <", value, "paymentTerm");
            return (Criteria) this;
        }

        public Criteria andPaymentTermLessThanOrEqualTo(Integer value) {
            addCriterion("payment_term <=", value, "paymentTerm");
            return (Criteria) this;
        }

        public Criteria andPaymentTermIn(List<Integer> values) {
            addCriterion("payment_term in", values, "paymentTerm");
            return (Criteria) this;
        }

        public Criteria andPaymentTermNotIn(List<Integer> values) {
            addCriterion("payment_term not in", values, "paymentTerm");
            return (Criteria) this;
        }

        public Criteria andPaymentTermBetween(Integer value1, Integer value2) {
            addCriterion("payment_term between", value1, value2, "paymentTerm");
            return (Criteria) this;
        }

        public Criteria andPaymentTermNotBetween(Integer value1, Integer value2) {
            addCriterion("payment_term not between", value1, value2, "paymentTerm");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountIsNull() {
            addCriterion("insurance_amount is null");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountIsNotNull() {
            addCriterion("insurance_amount is not null");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountEqualTo(Double value) {
            addCriterion("insurance_amount =", value, "insuranceAmount");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountNotEqualTo(Double value) {
            addCriterion("insurance_amount <>", value, "insuranceAmount");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountGreaterThan(Double value) {
            addCriterion("insurance_amount >", value, "insuranceAmount");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("insurance_amount >=", value, "insuranceAmount");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountLessThan(Double value) {
            addCriterion("insurance_amount <", value, "insuranceAmount");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountLessThanOrEqualTo(Double value) {
            addCriterion("insurance_amount <=", value, "insuranceAmount");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountIn(List<Double> values) {
            addCriterion("insurance_amount in", values, "insuranceAmount");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountNotIn(List<Double> values) {
            addCriterion("insurance_amount not in", values, "insuranceAmount");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountBetween(Double value1, Double value2) {
            addCriterion("insurance_amount between", value1, value2, "insuranceAmount");
            return (Criteria) this;
        }

        public Criteria andInsuranceAmountNotBetween(Double value1, Double value2) {
            addCriterion("insurance_amount not between", value1, value2, "insuranceAmount");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberIsNull() {
            addCriterion("insurance_number is null");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberIsNotNull() {
            addCriterion("insurance_number is not null");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberEqualTo(Integer value) {
            addCriterion("insurance_number =", value, "insuranceNumber");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberNotEqualTo(Integer value) {
            addCriterion("insurance_number <>", value, "insuranceNumber");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberGreaterThan(Integer value) {
            addCriterion("insurance_number >", value, "insuranceNumber");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("insurance_number >=", value, "insuranceNumber");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberLessThan(Integer value) {
            addCriterion("insurance_number <", value, "insuranceNumber");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberLessThanOrEqualTo(Integer value) {
            addCriterion("insurance_number <=", value, "insuranceNumber");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberIn(List<Integer> values) {
            addCriterion("insurance_number in", values, "insuranceNumber");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberNotIn(List<Integer> values) {
            addCriterion("insurance_number not in", values, "insuranceNumber");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberBetween(Integer value1, Integer value2) {
            addCriterion("insurance_number between", value1, value2, "insuranceNumber");
            return (Criteria) this;
        }

        public Criteria andInsuranceNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("insurance_number not between", value1, value2, "insuranceNumber");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountIsNull() {
            addCriterion("payment_amount is null");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountIsNotNull() {
            addCriterion("payment_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountEqualTo(Double value) {
            addCriterion("payment_amount =", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountNotEqualTo(Double value) {
            addCriterion("payment_amount <>", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountGreaterThan(Double value) {
            addCriterion("payment_amount >", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("payment_amount >=", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountLessThan(Double value) {
            addCriterion("payment_amount <", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountLessThanOrEqualTo(Double value) {
            addCriterion("payment_amount <=", value, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountIn(List<Double> values) {
            addCriterion("payment_amount in", values, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountNotIn(List<Double> values) {
            addCriterion("payment_amount not in", values, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountBetween(Double value1, Double value2) {
            addCriterion("payment_amount between", value1, value2, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andPaymentAmountNotBetween(Double value1, Double value2) {
            addCriterion("payment_amount not between", value1, value2, "paymentAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIsNull() {
            addCriterion("transaction_date is null");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIsNotNull() {
            addCriterion("transaction_date is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionDateEqualTo(Date value) {
            addCriterionForJDBCDate("transaction_date =", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("transaction_date <>", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateGreaterThan(Date value) {
            addCriterionForJDBCDate("transaction_date >", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("transaction_date >=", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateLessThan(Date value) {
            addCriterionForJDBCDate("transaction_date <", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("transaction_date <=", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIn(List<Date> values) {
            addCriterionForJDBCDate("transaction_date in", values, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("transaction_date not in", values, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("transaction_date between", value1, value2, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("transaction_date not between", value1, value2, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterionForJDBCDate("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateIsNull() {
            addCriterion("closing_date is null");
            return (Criteria) this;
        }

        public Criteria andClosingDateIsNotNull() {
            addCriterion("closing_date is not null");
            return (Criteria) this;
        }

        public Criteria andClosingDateEqualTo(Date value) {
            addCriterionForJDBCDate("closing_date =", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("closing_date <>", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateGreaterThan(Date value) {
            addCriterionForJDBCDate("closing_date >", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("closing_date >=", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateLessThan(Date value) {
            addCriterionForJDBCDate("closing_date <", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("closing_date <=", value, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateIn(List<Date> values) {
            addCriterionForJDBCDate("closing_date in", values, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("closing_date not in", values, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("closing_date between", value1, value2, "closingDate");
            return (Criteria) this;
        }

        public Criteria andClosingDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("closing_date not between", value1, value2, "closingDate");
            return (Criteria) this;
        }

        public Criteria andApplicantIdIsNull() {
            addCriterion("applicant_id is null");
            return (Criteria) this;
        }

        public Criteria andApplicantIdIsNotNull() {
            addCriterion("applicant_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplicantIdEqualTo(String value) {
            addCriterion("applicant_id =", value, "applicantId");
            return (Criteria) this;
        }

        public Criteria andApplicantIdNotEqualTo(String value) {
            addCriterion("applicant_id <>", value, "applicantId");
            return (Criteria) this;
        }

        public Criteria andApplicantIdGreaterThan(String value) {
            addCriterion("applicant_id >", value, "applicantId");
            return (Criteria) this;
        }

        public Criteria andApplicantIdGreaterThanOrEqualTo(String value) {
            addCriterion("applicant_id >=", value, "applicantId");
            return (Criteria) this;
        }

        public Criteria andApplicantIdLessThan(String value) {
            addCriterion("applicant_id <", value, "applicantId");
            return (Criteria) this;
        }

        public Criteria andApplicantIdLessThanOrEqualTo(String value) {
            addCriterion("applicant_id <=", value, "applicantId");
            return (Criteria) this;
        }

        public Criteria andApplicantIdLike(String value) {
            addCriterion("applicant_id like", value, "applicantId");
            return (Criteria) this;
        }

        public Criteria andApplicantIdNotLike(String value) {
            addCriterion("applicant_id not like", value, "applicantId");
            return (Criteria) this;
        }

        public Criteria andApplicantIdIn(List<String> values) {
            addCriterion("applicant_id in", values, "applicantId");
            return (Criteria) this;
        }

        public Criteria andApplicantIdNotIn(List<String> values) {
            addCriterion("applicant_id not in", values, "applicantId");
            return (Criteria) this;
        }

        public Criteria andApplicantIdBetween(String value1, String value2) {
            addCriterion("applicant_id between", value1, value2, "applicantId");
            return (Criteria) this;
        }

        public Criteria andApplicantIdNotBetween(String value1, String value2) {
            addCriterion("applicant_id not between", value1, value2, "applicantId");
            return (Criteria) this;
        }

        public Criteria andRelationshipIsNull() {
            addCriterion("relationship is null");
            return (Criteria) this;
        }

        public Criteria andRelationshipIsNotNull() {
            addCriterion("relationship is not null");
            return (Criteria) this;
        }

        public Criteria andRelationshipEqualTo(Integer value) {
            addCriterion("relationship =", value, "relationship");
            return (Criteria) this;
        }

        public Criteria andRelationshipNotEqualTo(Integer value) {
            addCriterion("relationship <>", value, "relationship");
            return (Criteria) this;
        }

        public Criteria andRelationshipGreaterThan(Integer value) {
            addCriterion("relationship >", value, "relationship");
            return (Criteria) this;
        }

        public Criteria andRelationshipGreaterThanOrEqualTo(Integer value) {
            addCriterion("relationship >=", value, "relationship");
            return (Criteria) this;
        }

        public Criteria andRelationshipLessThan(Integer value) {
            addCriterion("relationship <", value, "relationship");
            return (Criteria) this;
        }

        public Criteria andRelationshipLessThanOrEqualTo(Integer value) {
            addCriterion("relationship <=", value, "relationship");
            return (Criteria) this;
        }

        public Criteria andRelationshipIn(List<Integer> values) {
            addCriterion("relationship in", values, "relationship");
            return (Criteria) this;
        }

        public Criteria andRelationshipNotIn(List<Integer> values) {
            addCriterion("relationship not in", values, "relationship");
            return (Criteria) this;
        }

        public Criteria andRelationshipBetween(Integer value1, Integer value2) {
            addCriterion("relationship between", value1, value2, "relationship");
            return (Criteria) this;
        }

        public Criteria andRelationshipNotBetween(Integer value1, Integer value2) {
            addCriterion("relationship not between", value1, value2, "relationship");
            return (Criteria) this;
        }

        public Criteria andRelationship2IsNull() {
            addCriterion("relationship2 is null");
            return (Criteria) this;
        }

        public Criteria andRelationship2IsNotNull() {
            addCriterion("relationship2 is not null");
            return (Criteria) this;
        }

        public Criteria andRelationship2EqualTo(String value) {
            addCriterion("relationship2 =", value, "relationship2");
            return (Criteria) this;
        }

        public Criteria andRelationship2NotEqualTo(String value) {
            addCriterion("relationship2 <>", value, "relationship2");
            return (Criteria) this;
        }

        public Criteria andRelationship2GreaterThan(String value) {
            addCriterion("relationship2 >", value, "relationship2");
            return (Criteria) this;
        }

        public Criteria andRelationship2GreaterThanOrEqualTo(String value) {
            addCriterion("relationship2 >=", value, "relationship2");
            return (Criteria) this;
        }

        public Criteria andRelationship2LessThan(String value) {
            addCriterion("relationship2 <", value, "relationship2");
            return (Criteria) this;
        }

        public Criteria andRelationship2LessThanOrEqualTo(String value) {
            addCriterion("relationship2 <=", value, "relationship2");
            return (Criteria) this;
        }

        public Criteria andRelationship2Like(String value) {
            addCriterion("relationship2 like", value, "relationship2");
            return (Criteria) this;
        }

        public Criteria andRelationship2NotLike(String value) {
            addCriterion("relationship2 not like", value, "relationship2");
            return (Criteria) this;
        }

        public Criteria andRelationship2In(List<String> values) {
            addCriterion("relationship2 in", values, "relationship2");
            return (Criteria) this;
        }

        public Criteria andRelationship2NotIn(List<String> values) {
            addCriterion("relationship2 not in", values, "relationship2");
            return (Criteria) this;
        }

        public Criteria andRelationship2Between(String value1, String value2) {
            addCriterion("relationship2 between", value1, value2, "relationship2");
            return (Criteria) this;
        }

        public Criteria andRelationship2NotBetween(String value1, String value2) {
            addCriterion("relationship2 not between", value1, value2, "relationship2");
            return (Criteria) this;
        }

        public Criteria andInsuredIdIsNull() {
            addCriterion("insured_id is null");
            return (Criteria) this;
        }

        public Criteria andInsuredIdIsNotNull() {
            addCriterion("insured_id is not null");
            return (Criteria) this;
        }

        public Criteria andInsuredIdEqualTo(String value) {
            addCriterion("insured_id =", value, "insuredId");
            return (Criteria) this;
        }

        public Criteria andInsuredIdNotEqualTo(String value) {
            addCriterion("insured_id <>", value, "insuredId");
            return (Criteria) this;
        }

        public Criteria andInsuredIdGreaterThan(String value) {
            addCriterion("insured_id >", value, "insuredId");
            return (Criteria) this;
        }

        public Criteria andInsuredIdGreaterThanOrEqualTo(String value) {
            addCriterion("insured_id >=", value, "insuredId");
            return (Criteria) this;
        }

        public Criteria andInsuredIdLessThan(String value) {
            addCriterion("insured_id <", value, "insuredId");
            return (Criteria) this;
        }

        public Criteria andInsuredIdLessThanOrEqualTo(String value) {
            addCriterion("insured_id <=", value, "insuredId");
            return (Criteria) this;
        }

        public Criteria andInsuredIdLike(String value) {
            addCriterion("insured_id like", value, "insuredId");
            return (Criteria) this;
        }

        public Criteria andInsuredIdNotLike(String value) {
            addCriterion("insured_id not like", value, "insuredId");
            return (Criteria) this;
        }

        public Criteria andInsuredIdIn(List<String> values) {
            addCriterion("insured_id in", values, "insuredId");
            return (Criteria) this;
        }

        public Criteria andInsuredIdNotIn(List<String> values) {
            addCriterion("insured_id not in", values, "insuredId");
            return (Criteria) this;
        }

        public Criteria andInsuredIdBetween(String value1, String value2) {
            addCriterion("insured_id between", value1, value2, "insuredId");
            return (Criteria) this;
        }

        public Criteria andInsuredIdNotBetween(String value1, String value2) {
            addCriterion("insured_id not between", value1, value2, "insuredId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNull() {
            addCriterion("employee_id is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNotNull() {
            addCriterion("employee_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdEqualTo(String value) {
            addCriterion("employee_id =", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotEqualTo(String value) {
            addCriterion("employee_id <>", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThan(String value) {
            addCriterion("employee_id >", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThanOrEqualTo(String value) {
            addCriterion("employee_id >=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThan(String value) {
            addCriterion("employee_id <", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThanOrEqualTo(String value) {
            addCriterion("employee_id <=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLike(String value) {
            addCriterion("employee_id like", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotLike(String value) {
            addCriterion("employee_id not like", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIn(List<String> values) {
            addCriterion("employee_id in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotIn(List<String> values) {
            addCriterion("employee_id not in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdBetween(String value1, String value2) {
            addCriterion("employee_id between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotBetween(String value1, String value2) {
            addCriterion("employee_id not between", value1, value2, "employeeId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}