package com.mrbt.insurance.webset.model;

public class ProductInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.comp_id
     *
     * @mbggenerated
     */
    private Integer compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.pname
     *
     * @mbggenerated
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.element
     *
     * @mbggenerated
     */
    private String element;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.rate
     *
     * @mbggenerated
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.overview
     *
     * @mbggenerated
     */
    private String overview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.details
     *
     * @mbggenerated
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.sample
     *
     * @mbggenerated
     */
    private String sample;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.notice
     *
     * @mbggenerated
     */
    private String notice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.problem
     *
     * @mbggenerated
     */
    private String problem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.prompt
     *
     * @mbggenerated
     */
    private String prompt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.sataement
     *
     * @mbggenerated
     */
    private String sataement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.healthy
     *
     * @mbggenerated
     */
    private String healthy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.ptype
     *
     * @mbggenerated
     */
    private Integer ptype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.id
     *
     * @return the value of product_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.id
     *
     * @param id the value for product_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.comp_id
     *
     * @return the value of product_info.comp_id
     *
     * @mbggenerated
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.comp_id
     *
     * @param compId the value for product_info.comp_id
     *
     * @mbggenerated
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.pname
     *
     * @return the value of product_info.pname
     *
     * @mbggenerated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.pname
     *
     * @param pname the value for product_info.pname
     *
     * @mbggenerated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.element
     *
     * @return the value of product_info.element
     *
     * @mbggenerated
     */
    public String getElement() {
        return element;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.element
     *
     * @param element the value for product_info.element
     *
     * @mbggenerated
     */
    public void setElement(String element) {
        this.element = element == null ? null : element.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.rate
     *
     * @return the value of product_info.rate
     *
     * @mbggenerated
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.rate
     *
     * @param rate the value for product_info.rate
     *
     * @mbggenerated
     */
    public void setRate(String rate) {
        this.rate = rate == null ? null : rate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.overview
     *
     * @return the value of product_info.overview
     *
     * @mbggenerated
     */
    public String getOverview() {
        return overview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.overview
     *
     * @param overview the value for product_info.overview
     *
     * @mbggenerated
     */
    public void setOverview(String overview) {
        this.overview = overview == null ? null : overview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.details
     *
     * @return the value of product_info.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.details
     *
     * @param details the value for product_info.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.sample
     *
     * @return the value of product_info.sample
     *
     * @mbggenerated
     */
    public String getSample() {
        return sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.sample
     *
     * @param sample the value for product_info.sample
     *
     * @mbggenerated
     */
    public void setSample(String sample) {
        this.sample = sample == null ? null : sample.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.notice
     *
     * @return the value of product_info.notice
     *
     * @mbggenerated
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.notice
     *
     * @param notice the value for product_info.notice
     *
     * @mbggenerated
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.problem
     *
     * @return the value of product_info.problem
     *
     * @mbggenerated
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.problem
     *
     * @param problem the value for product_info.problem
     *
     * @mbggenerated
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.prompt
     *
     * @return the value of product_info.prompt
     *
     * @mbggenerated
     */
    public String getPrompt() {
        return prompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.prompt
     *
     * @param prompt the value for product_info.prompt
     *
     * @mbggenerated
     */
    public void setPrompt(String prompt) {
        this.prompt = prompt == null ? null : prompt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.sataement
     *
     * @return the value of product_info.sataement
     *
     * @mbggenerated
     */
    public String getSataement() {
        return sataement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.sataement
     *
     * @param sataement the value for product_info.sataement
     *
     * @mbggenerated
     */
    public void setSataement(String sataement) {
        this.sataement = sataement == null ? null : sataement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.healthy
     *
     * @return the value of product_info.healthy
     *
     * @mbggenerated
     */
    public String getHealthy() {
        return healthy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.healthy
     *
     * @param healthy the value for product_info.healthy
     *
     * @mbggenerated
     */
    public void setHealthy(String healthy) {
        this.healthy = healthy == null ? null : healthy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.ptype
     *
     * @return the value of product_info.ptype
     *
     * @mbggenerated
     */
    public Integer getPtype() {
        return ptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.ptype
     *
     * @param ptype the value for product_info.ptype
     *
     * @mbggenerated
     */
    public void setPtype(Integer ptype) {
        this.ptype = ptype;
    }
}