package com.mrbt.insurance.webset.model;

import java.util.Date;

public class TrafficWebsite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_website.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_website.browse_number
     *
     * @mbggenerated
     */
    private Integer browseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_website.browse_id
     *
     * @mbggenerated
     */
    private String browseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_website.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_website.id
     *
     * @return the value of traffic_website.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_website.id
     *
     * @param id the value for traffic_website.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_website.browse_number
     *
     * @return the value of traffic_website.browse_number
     *
     * @mbggenerated
     */
    public Integer getBrowseNumber() {
        return browseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_website.browse_number
     *
     * @param browseNumber the value for traffic_website.browse_number
     *
     * @mbggenerated
     */
    public void setBrowseNumber(Integer browseNumber) {
        this.browseNumber = browseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_website.browse_id
     *
     * @return the value of traffic_website.browse_id
     *
     * @mbggenerated
     */
    public String getBrowseId() {
        return browseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_website.browse_id
     *
     * @param browseId the value for traffic_website.browse_id
     *
     * @mbggenerated
     */
    public void setBrowseId(String browseId) {
        this.browseId = browseId == null ? null : browseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_website.create_time
     *
     * @return the value of traffic_website.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_website.create_time
     *
     * @param createTime the value for traffic_website.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}