package com.mrbt.insurance.webset.model;

import java.util.Date;

public class UsersPolicyHolder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_policy_holder.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_policy_holder.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_policy_holder.document_id
     *
     * @mbggenerated
     */
    private Integer documentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_policy_holder.document_code
     *
     * @mbggenerated
     */
    private String documentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_policy_holder.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_policy_holder.brithday
     *
     * @mbggenerated
     */
    private Date brithday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_policy_holder.telephone
     *
     * @mbggenerated
     */
    private Integer telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_policy_holder.regis_time
     *
     * @mbggenerated
     */
    private Date regisTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_policy_holder.u_id
     *
     * @mbggenerated
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_policy_holder.integral
     *
     * @mbggenerated
     */
    private Integer integral;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_policy_holder.id
     *
     * @return the value of users_policy_holder.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_policy_holder.id
     *
     * @param id the value for users_policy_holder.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_policy_holder.uname
     *
     * @return the value of users_policy_holder.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_policy_holder.uname
     *
     * @param uname the value for users_policy_holder.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_policy_holder.document_id
     *
     * @return the value of users_policy_holder.document_id
     *
     * @mbggenerated
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_policy_holder.document_id
     *
     * @param documentId the value for users_policy_holder.document_id
     *
     * @mbggenerated
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_policy_holder.document_code
     *
     * @return the value of users_policy_holder.document_code
     *
     * @mbggenerated
     */
    public String getDocumentCode() {
        return documentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_policy_holder.document_code
     *
     * @param documentCode the value for users_policy_holder.document_code
     *
     * @mbggenerated
     */
    public void setDocumentCode(String documentCode) {
        this.documentCode = documentCode == null ? null : documentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_policy_holder.sex
     *
     * @return the value of users_policy_holder.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_policy_holder.sex
     *
     * @param sex the value for users_policy_holder.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_policy_holder.brithday
     *
     * @return the value of users_policy_holder.brithday
     *
     * @mbggenerated
     */
    public Date getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_policy_holder.brithday
     *
     * @param brithday the value for users_policy_holder.brithday
     *
     * @mbggenerated
     */
    public void setBrithday(Date brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_policy_holder.telephone
     *
     * @return the value of users_policy_holder.telephone
     *
     * @mbggenerated
     */
    public Integer getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_policy_holder.telephone
     *
     * @param telephone the value for users_policy_holder.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_policy_holder.regis_time
     *
     * @return the value of users_policy_holder.regis_time
     *
     * @mbggenerated
     */
    public Date getRegisTime() {
        return regisTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_policy_holder.regis_time
     *
     * @param regisTime the value for users_policy_holder.regis_time
     *
     * @mbggenerated
     */
    public void setRegisTime(Date regisTime) {
        this.regisTime = regisTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_policy_holder.u_id
     *
     * @return the value of users_policy_holder.u_id
     *
     * @mbggenerated
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_policy_holder.u_id
     *
     * @param uId the value for users_policy_holder.u_id
     *
     * @mbggenerated
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_policy_holder.integral
     *
     * @return the value of users_policy_holder.integral
     *
     * @mbggenerated
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_policy_holder.integral
     *
     * @param integral the value for users_policy_holder.integral
     *
     * @mbggenerated
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }
}