package com.mrbt.insurance.webset.model;

import java.util.Date;

public class UsersInsuredInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_insured_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_insured_info.iname
     *
     * @mbggenerated
     */
    private String iname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_insured_info.document_id
     *
     * @mbggenerated
     */
    private Integer documentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_insured_info.doucument_code
     *
     * @mbggenerated
     */
    private String doucumentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_insured_info.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_insured_info.dirthday
     *
     * @mbggenerated
     */
    private Date dirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_insured_info.telephone
     *
     * @mbggenerated
     */
    private Integer telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_insured_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_insured_info.id
     *
     * @return the value of users_insured_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_insured_info.id
     *
     * @param id the value for users_insured_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_insured_info.iname
     *
     * @return the value of users_insured_info.iname
     *
     * @mbggenerated
     */
    public String getIname() {
        return iname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_insured_info.iname
     *
     * @param iname the value for users_insured_info.iname
     *
     * @mbggenerated
     */
    public void setIname(String iname) {
        this.iname = iname == null ? null : iname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_insured_info.document_id
     *
     * @return the value of users_insured_info.document_id
     *
     * @mbggenerated
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_insured_info.document_id
     *
     * @param documentId the value for users_insured_info.document_id
     *
     * @mbggenerated
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_insured_info.doucument_code
     *
     * @return the value of users_insured_info.doucument_code
     *
     * @mbggenerated
     */
    public String getDoucumentCode() {
        return doucumentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_insured_info.doucument_code
     *
     * @param doucumentCode the value for users_insured_info.doucument_code
     *
     * @mbggenerated
     */
    public void setDoucumentCode(String doucumentCode) {
        this.doucumentCode = doucumentCode == null ? null : doucumentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_insured_info.sex
     *
     * @return the value of users_insured_info.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_insured_info.sex
     *
     * @param sex the value for users_insured_info.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_insured_info.dirthday
     *
     * @return the value of users_insured_info.dirthday
     *
     * @mbggenerated
     */
    public Date getDirthday() {
        return dirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_insured_info.dirthday
     *
     * @param dirthday the value for users_insured_info.dirthday
     *
     * @mbggenerated
     */
    public void setDirthday(Date dirthday) {
        this.dirthday = dirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_insured_info.telephone
     *
     * @return the value of users_insured_info.telephone
     *
     * @mbggenerated
     */
    public Integer getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_insured_info.telephone
     *
     * @param telephone the value for users_insured_info.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_insured_info.create_time
     *
     * @return the value of users_insured_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_insured_info.create_time
     *
     * @param createTime the value for users_insured_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}