package com.mrbt.insurance.webset.model;

public class UsersDocumentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_document_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_document_info.document_name
     *
     * @mbggenerated
     */
    private String documentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_document_info.id
     *
     * @return the value of users_document_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_document_info.id
     *
     * @param id the value for users_document_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_document_info.document_name
     *
     * @return the value of users_document_info.document_name
     *
     * @mbggenerated
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_document_info.document_name
     *
     * @param documentName the value for users_document_info.document_name
     *
     * @mbggenerated
     */
    public void setDocumentName(String documentName) {
        this.documentName = documentName == null ? null : documentName.trim();
    }
}